### PR TITLE
Fix race condition

### LINKED ISSUE #157: Race condition in storage/registry logging
go test detected race condition:

```console
==================
WARNING: DATA RACE
Write at 0x00c000379650 by goroutine 38:
  runtime.mapassign_faststr()
      /usr/local/go/src/runtime/map_faststr.go:190 +0x0
  github.com/Peripli/service-manager/vendor/github.com/onrik/logrus/filename.(*Hook).Fire()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onrik/logrus/filename/filename.go:23 +0x1a5
  github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus.LevelHooks.Fire()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus/hooks.go:28 +0xc1
  github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus.(*Entry).fireHooks()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus/entry.go:133 +0x128
  github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus.Entry.log()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus/entry.go:111 +0x1ac
  github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus.(*Entry).Debug()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus/entry.go:155 +0x173
  github.com/Peripli/service-manager/storage.awaitTermination()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/storage/registry.go:67 +0xef

Previous read at 0x00c000379650 by goroutine 73:
  runtime.mapaccess2_faststr()
      /usr/local/go/src/runtime/map_faststr.go:101 +0x0
  github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus.prefixFieldClashes()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus/formatter.go:35 +0xe4
  github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus.(*TextFormatter).Format()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus/text_formatter.go:83 +0xb6
  github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus.(*Entry).write()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus/entry.go:140 +0x9b
  github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus.Entry.log()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus/entry.go:118 +0x2ca
  github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus.(*Entry).Debug()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/sirupsen/logrus/entry.go:155 +0x173
  github.com/Peripli/service-manager/storage.awaitTermination()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/storage/registry.go:67 +0xef

Goroutine 38 (running) created at:
  github.com/Peripli/service-manager/storage.Use()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/storage/registry.go:60 +0x35e
  github.com/Peripli/service-manager/pkg/sm.New()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/pkg/sm/sm.go:95 +0x514
  github.com/Peripli/service-manager/test/sm_test.glob..func1.3.5.1()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/test/sm/sm_test.go:115 +0xa6
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113 +0xbd
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:64 +0x16a
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes/it_node.go:26 +0xa2
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:203 +0x766
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0x145
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x172
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x4ad
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:203 +0x766
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0x145
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x172
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x4ad
  github.com/Peripli/service-manager/vendor/github.com/onsi/gomega/internal/assertion.(*Assertion).To()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:35 +0xd0
  github.com/Peripli/service-manager/test/sm_test.glob..func1.3.3.1()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/test/sm/sm_test.go:99 +0x226
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113 +0xbd
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:64 +0x16a
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes/it_node.go:26 +0xa2
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:203 +0x766
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0x145
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x172
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x4ad
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:203 +0x766
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0x145
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x172
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x4ad
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:203 +0x766
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0x145
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x172
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x4ad
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:66 +0x149
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/suite.(*Suite).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:62 +0x3e1
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo.RunSpecsWithCustomReporters()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:221 +0x367
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo.RunSpecs()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:202 +0x99
  github.com/Peripli/service-manager/test/sm_test.TestServiceManager()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/test/sm/sm_test.go:44 +0x84
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:827 +0x162

Goroutine 73 (running) created at:
  github.com/Peripli/service-manager/storage.Use()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/storage/registry.go:60 +0x35e
  github.com/Peripli/service-manager/pkg/sm.New()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/pkg/sm/sm.go:95 +0x514
  github.com/Peripli/service-manager/test/sm_test.glob..func1.3.7.1()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/test/sm/sm_test.go:137 +0xac
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113 +0xbd
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:64 +0x16a
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes/it_node.go:26 +0xa2
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:203 +0x766
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0x145
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x172
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x4ad
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:203 +0x766
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0x145
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x172
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x4ad
  github.com/Peripli/service-manager/vendor/github.com/onsi/gomega/internal/assertion.(*Assertion).To()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:35 +0xd0
  github.com/Peripli/service-manager/test/sm_test.glob..func1.3.3.1()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/test/sm/sm_test.go:99 +0x226
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113 +0xbd
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:64 +0x16a
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/leafnodes/it_node.go:26 +0xa2
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:203 +0x766
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0x145
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x172
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x4ad
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:203 +0x766
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0x145
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x172
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x4ad
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:203 +0x766
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0x145
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x172
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x4ad
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:66 +0x149
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/suite.(*Suite).Run()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:62 +0x3e1
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo.RunSpecsWithCustomReporters()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:221 +0x367
  github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo.RunSpecs()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:202 +0x99
  github.com/Peripli/service-manager/test/sm_test.TestServiceManager()
      /Users/i322053/goworkspace/src/github.com/Peripli/service-manager/test/sm/sm_test.go:44 +0x84
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:827 +0x162
==================
--- FAIL: TestServiceManager (0.67s)
    testing.go:771: race detected during execution of test
==================
```

### PR DESCRIPTION
**Pull request by dpanayotov**
Fixes #157 
There are a couple issues:
1. `sm.New` wants to configure the default entry (write) but `util.HandleInterrupts` starts a goroutine that wants to read the default entry in order to copy it (read). Any goroutines that use logging must be started after the `log.Configure` call. Not the best solution. Same applies to `pkg/storage/registry.go - awaitTermination`
2. Because we share the same entry for all log events in a context, there is a race condition in the `onrik/logrus/filename` hook that adds the filename and location of the log - 
 https://github.com/onrik/logrus/blob/master/filename/filename.go#L24 Here, the same logrus.Entry is shared between the `until.HandleInterrupts` goroutine and the main service-manager goroutine (out of any http request).  `util.HandleInterrupts` invokes the hook which wants to write in the entry's data map, but at the same time the main goroutine also wants to log, writing to the same entry map. Solution is to copy the entry for every log. Again, not the best solution...

Overall, this is a workaround, that comes from abusing the logrus library. The logrus.Logger has sync.Pool that doesn't share entries and uses proper synchronization, but doesn't fit our needs because it doesn't expose the `Data` field in which we want to store context (request-scoped) information. 

Explore and see if other logging libraries fit our needs:
- https://github.com/uber-go/zap
- https://github.com/rs/zerolog
- https://github.com/cloudfoundry/lager

### CODE REVIEW

File: pkg/sm/sm.go [hunk 1]
```diff
@@ -89,6 +91,9 @@ func New(ctx context.Context, env env.Environment) *ServiceManagerBuilder {
 	// setup logging
 	ctx = log.Configure(ctx, cfg.Log)
 
+	// goroutines that log must be started after the log has been configured
+	util.HandleInterrupts(ctx, cancel)
```
Comment (KirilKabakchiev) [inline pkg/sm/sm.go]: can we put it in the server for now ? otherwise we gotta do the same in proxy.go

Comment (dpanayotov) [reply pkg/sm/sm.go]: I agree we'd have to copy it, but in the server seems to be too late. Calls to the database, as well as spawning a new goroutine happen before the server is created. If anything fails, the storage might not be closed and goroutines will leak

**Comment by dzahariev** [comment]
Please adapt in SBProxies.
@dpanayotov
