### PR TITLE
Lock when generating encryption key

### LINKED ISSUE #106: Failure to start when generating encryption key
When service-manager runs on more than 1 node, generating encryption key for the first time might fail. This happens because all nodes get that there is no encryption key and all try to generate one. However, if one generates before the others, others will fail because only 1 encryption key can be set.

### PR DESCRIPTION
**Pull request by dpanayotov**
Fixes #106 

Opened #116 for test

### CODE REVIEW

File: pkg/sm/encryption.go [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+func waitForLeader(keyFetcher security.KeyFetcher) error {
+	var encryptionKey []byte
+	for i := 0; i < 5; i++ {
+		logrus.Debugf("Waiting for leader to generate encryption key...")
+		encryptionKey, err := keyFetcher.GetEncryptionKey()
+		if err != nil {
+			return err
+		}
+		if len(encryptionKey) != 0 {
+			return nil
```
Comment (dzahariev) [inline pkg/sm/encryption.go]: I think here you should return the key instead null

File: pkg/sm/sm.go [hunk 2]
```diff
@@ -155,6 +155,9 @@ func (smb *ServiceManagerBuilder) Build() *ServiceManager {
 }
 
 func initializeSecureStorage(secureStorage storage.Security) error {
+	if err := secureStorage.Lock(); err != nil {
+		return err
```
Comment (pankrator) [inline pkg/sm/sm.go]: We don't want to return an error if database is locked. I think it should be:
1) Try to lock database.
2) If it is already locked, then wait some time (2 seconds for example)
3) Try to lock again
4) Repeat several times(5 for example)
5) If it couldn't acquire the lock, then panic
6) If lock is acquired then check for the encryption key. If it is already there then do nothing, otherwise generate one

Comment (pankrator) [reply pkg/sm/sm.go]: It appears that advisory locks block until a lock can be acquired: 
https://medium.com/@codeflows/application-level-locking-with-postgres-advisory-locks-c29759eeb7a7

File: test/main_test.go [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+		session.Kill()
+		session2.Kill()
+		os.Unsetenv("API_TOKEN_ISSUER_URL")
+	})
+	Context("when more than one instance is started", func() {
+		It("should wait for lock", func() {
+			if os.Getenv("CLEAN_ENV") == "" {
+				Skip("Environment is not clean to validate behavior of parallel encryption key generation")
+			} else {
+				command := exec.Command(binaryPath)
```
Comment (KirilKabakchiev) [inline test/main_test.go]: pass port as flag here so both can use different ports

File: storage/postgres/security.go [hunk 4]
```diff
@@ -25,9 +25,40 @@ import (
...
 type securityStorage struct {
 	db            *sqlx.DB
 	encryptionKey []byte
+	isLocked      bool
+}
+
+// Lock acquires a database lock so that only one process can manipulate the encryption key.
+// Returns an error if the process has already acquired the lock
+func (s *securityStorage) Lock() error {
+	if s.isLocked {
```
Comment (KirilKabakchiev) [inline storage/postgres/security.go]: add a mutex here to safeguard from future possible raceconditions

File: storage/postgres/security.go [hunk 5]
```diff
@@ -25,9 +25,40 @@ import (
...
+	if err != nil {
+		return err
+	}
+	s.isLocked = true
+	return nil
+}
+
+// Unlock releases the database lock.
+func (s *securityStorage) Unlock() error {
+	if !s.isLocked {
```
Comment (KirilKabakchiev) [inline storage/postgres/security.go]: add a mutex here to safeguard from future possible raceconditions

File: storage/postgres/security.go [hunk 6]
```diff
@@ -17,17 +17,53 @@
...
 	db            *sqlx.DB
 	encryptionKey []byte
+	isLocked      bool
+	mutex         *sync.Mutex
+}
+
+// Lock acquires a database lock so that only one process can manipulate the encryption key.
+// Returns an error if the process has already acquired the lock
+func (s *securityStorage) Lock(ctx context.Context) error {
+	s.mutex.Lock()
```
Comment (KirilKabakchiev) [inline storage/postgres/security.go]: is this the correct lock ( e.x. this or RWLock )

Comment (dpanayotov) [reply storage/postgres/security.go]: RWMutex provides only R(W)Lock and R(W)Unlock for these explicit situations. RWMutext.Lock/Unlock is the same as Mutex.Lock/Unlock
Since this is both reading and writing the value, there's no difference between RWMutex.Lock and Mutex.Lock
